#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
tmux kill-session -t ts3ldap; tmux new-session -d -s "ts3ldap" "node app.js > ./logs/log.txt"; tmux set-option -t eas:0 remain-on-exit; tmux attach -t ts3ldap
